# Generated by Django 2.1 on 2018-08-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='photo',
            field=models.ImageField(blank=True, upload_to='category_images'),
        ),
    ]
